# Generated by Django 4.0.4 on 2022-04-19 13:05

from django.db import migrations
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_blogpost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='state',
            field=django_fsm.FSMField(choices=[('draft', 'Draft'), ('waiting_approval', 'Waiting Approval'), ('published', 'Published')], default='draft', max_length=50),
        ),
    ]
